language: java

jdk:
- openjdk7

install: ant

addons:
  debug: true
  artifacts: true
  region: "Frankfurt"
  endpoint: "evaltravis.s3-website.eu-central-1.amazonaws.com"
  paths:
  -  $(git ls-files -o | tr "\n" ":")
  
