language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8

before_install:
- cat /etc/mavenrc
- cat /home/travis/build.sh

install:
- ant

script:
- java -version
- java -version > result.txt
- pwd
- "ls -la"

deploy:
  provider: bintray
  file: bintray.desc.json
  user: peterkir
  key:
    secure: UNRNbIII5utNld2a7w3t9ErmzSMAHF3mFibGdGJE6/374rwN4PBNJLt+xPxC70RYCgva+iAERtdCLKwC6EMwIfR9itfUPZ8TB7df+XHqXDtQOOB/dmr2h6WNROT7jePDnxGfeFkbIosM3LiYE80TfY6wDPn3KmgfgS5xDAyTMp0=
  dry-run: true

