language: java

jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8

before_install:
- cat /etc/mavenrc
- cat /home/travis/build.sh

install: 
- ant

script:
- java -version


#addons:
#    artifacts: true
#    debug: true
#    region: eu-west-1
#    skip_cleanup: true
#    paths:
#    - $(git ls-files -o | tr "\n" ":")
#    upload-dir: artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER

#deploy:
#  provider: s3
#  bucket: eval.s3
#  region: eu-west-1
#  local_dir: /home/travis/build/peterkir/eval/
#  upload-dir: artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
#  skip_cleanup: true
#  acl: public_read
#  on:
#    repo: peterkir/eval
