language: java

jdk:
- oraclejdk6
- oraclejdk7
- oraclejdk8
- openjdk7
- openjdk8

install: ant

deploy:
  provider: s3
  access_key_id: AKIAI6FGWB26WLJZHBRQ
  secret_access_key:
    secure: frLJglOKleJZWLg+SSaidVF+YEyC10qzc/rLlrI9Dltjcid3JMFd8gkB21tZdW9bP9HYpDw6cjNAvQoiYia+PXm3hNau6FelDK5s76g9xkyY2Il2occMM/icQBizVxEACHWo3zQgB2hlJbgn3Y0IOJuVhr7ioxLzxovfvq+wJdg=
  bucket: eval.s3
  region: eu-west-1
  local_dir: .
  upload-dir: artifacts/$TRAVIS_JOB_NUMBER
  acl: public_read
  on:
    repo: peterkir/eval
